[phases.setup]
nixPkgs = ["python3", "python311Packages.requests"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
